UniceSIL\SyllabusApogeeImporterBundle\Entity\NatureElp:
    type: entity
    table: NATURE_ELP
    id:
        codNel:
            type: string
            nullable: false
            length: 4
            options:
                fixed: false
                comment: 'Code Nature Element Pedagogique'
            id: true
            column: COD_NEL
            generator:
                strategy: SEQUENCE
    fields:
        libNel:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
                comment: 'Libelle Long Nature Element Pedagogique'
            column: LIB_NEL
        licNel:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
                comment: 'Libelle Court Nature Element Pedagogique'
            column: LIC_NEL
        temEnSveNel:
            type: string
            nullable: false
            length: 1
            options:
                fixed: false
                comment: 'Temoin Code en Service'
                default: O
            column: TEM_EN_SVE_NEL
        temUe:
            type: string
            nullable: false
            length: 1
            options:
                fixed: false
                comment: 'Témoin indiquant si l''élément pédagogique est de type Unité Enseignement'
                default: 'N'
            column: TEM_UE
        temSemestre:
            type: string
            nullable: false
            length: 1
            options:
                fixed: false
                comment: 'Témoin indiquant si l''élément pédagogique est de type Semestre'
                default: 'N'
            column: TEM_SEMESTRE
        temFictif:
            type: string
            nullable: false
            length: 1
            options:
                fixed: false
                comment: 'Témoin indiquant si l''élément pédagogique est de type Fictif'
                default: 'N'
            column: TEM_FICTIF
    lifecycleCallbacks: {  }
