UniceSIL\SyllabusApogeeImporterBundle\Entity\SpecialiteVdi:
    type: entity
    table: SPECIALITE_VDI
    id:
        codSvd:
            type: string
            nullable: false
            length: 6
            options:
                fixed: false
                comment: 'code de la specialite'
            id: true
            column: COD_SVD
            generator:
                strategy: SEQUENCE
    fields:
        libSvd:
            type: string
            nullable: false
            length: 400
            options:
                fixed: false
                comment: 'libelle de la specialite'
            column: LIB_SVD
        temEnSveSvd:
            type: string
            nullable: false
            length: 1
            options:
                fixed: false
                comment: 'temoin de mise en service de la specialite'
                default: O
            column: TEM_EN_SVE_SVD
    lifecycleCallbacks: {  }
